
// Objective-C API for talking to the following Go packages
//
//	bp.com/gs1barcodegen
//
// File is generated by gomobile bind. Do not edit.
#ifndef __Gs1barcodegen_FRAMEWORK_H__
#define __Gs1barcodegen_FRAMEWORK_H__

#include "Gs1barcodegen.objc.h"
#include "Universe.objc.h"

#endif
