// Objective-C API for talking to bp.com/gs1barcodegen Go package.
//   gobind -lang=objc bp.com/gs1barcodegen
//
// File is generated by gobind. Do not edit.

#ifndef __Gs1barcodegen_H__
#define __Gs1barcodegen_H__

@import Foundation;
#include "ref.h"
#include "Universe.objc.h"


FOUNDATION_EXPORT NSString* _Nonnull Gs1barcodegenGenerateGS1BarcodeIntoBase64EncodedPNG(NSString* _Nullable stringToEmbed, long width, long height, NSError* _Nullable* _Nullable error);

#endif
